server:
  port: 8005
  

management:
 endpoints:
  web:

   exposure:
    include: '*'



spring:
  application:
    name: TECH-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/employeedb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate :
        dialect: org.hibernate.dialect.MySQL8Dialect

        
        
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.uuid} 

